# Generated by Django 4.2.11 on 2024-05-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(default='2a052c2e-2b18-4263-b63d-d7b7795aaf60', max_length=255, primary_key=True, serialize=False),
        ),
    ]
