# Generated by Django 4.2.11 on 2024-05-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='citizen_id',
            field=models.CharField(default='a48f4523-bd50-4217-8339-7797c87a8a08', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(default='24eb814a-2f86-4808-9c53-b562ce503ffb', max_length=255, primary_key=True, serialize=False),
        ),
    ]
