# Generated by Django 4.2.11 on 2024-05-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_alter_citizen_citizen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
