# Generated by Django 4.2.11 on 2024-05-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0003_alter_citizen_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
