# Generated by Django 4.2.11 on 2024-05-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('citizen', '0004_alter_citizen_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='groups',
            field=models.ManyToManyField(related_name='citizen_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='user_permissions',
            field=models.ManyToManyField(related_name='citizen_user_permissions', to='auth.permission'),
        ),
    ]
