# Generated by Django 4.2.11 on 2024-05-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='press_id',
            field=models.CharField(default='3b3eed63-98f6-4426-bc70-847182a489fd', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presspost',
            name='post_id',
            field=models.CharField(default='2473d05b-146f-482c-9f40-b7191fd64bb0', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presspost',
            name='press_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='press.press'),
        ),
    ]
