# Generated by Django 4.2.11 on 2024-05-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0002_presspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presspost',
            name='post_id',
            field=models.CharField(default='2df24146-f3c5-4fa5-ac11-5c54c4f84f36', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presspost',
            name='press_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='press.press'),
        ),
    ]
