# Generated by Django 4.2.11 on 2024-05-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0003_alter_presspost_post_id_alter_presspost_press_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presspost',
            name='post_id',
            field=models.CharField(default='cf843e6e-5a28-4438-b41d-fdeb0edcdcf1', max_length=255, primary_key=True, serialize=False),
        ),
    ]
