# Generated by Django 4.2.11 on 2024-05-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0004_alter_presspost_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presspost',
            name='post_id',
            field=models.CharField(default='60dcf8db-386e-4356-a7e1-ae4561d08bc5', max_length=255, primary_key=True, serialize=False),
        ),
    ]
